namespace Base
{
    public enum EventIdType
    {
        NumbericChange,
        PlayerAttrChange,
        ReloadConfigFinish,
        PositionChange,
        ReLoadConfigFinish,
        PlayerControlUnitCreated,
        TopInfoHeadIconClick,
        TopInfoHeadIconDoubleClick,
        UnitRefreshSkill,
        ErrorLog,
        NetworkChannelError,
        UnitCreate,
        UnitAddSkill,
        UnitRemoveSkill,
        CameraLoadComplete,
        InitSceneStart,
        SceneInit,
        LoadingSceneStart,
        LoadingSceneUpdate,
        LauncherSceneStart,
        LauncherSceneUpdate,
        LauncherStartUpdateLauncher,
        LauncherStartUpdateGame,
		
        MouseRightButtonDown,
        MouseLeftButtonDown,
        MouseRightButtonDownClickUnit,
        MouseRightButtonDownClickMap,
        MouseLeftButtonDownClickUnit,
        MouseLiftButtonDownClickMap,
        MouseButtonDown,

        MouseLeftButtonUp,
        MouseRightButtonUp,

        MouseLongClick,
		
        BuffSetExpiration,

        /// <summary>
        /// 这个事件发生在Buff被移除之前
        /// </summary>
        UnitUpdateBuff,

        UnitBuffAdd,
        Ping,
        SmallMapLeftDragEvent,
        PlayCombatNumber,

        /// <summary>
        /// 在Unit被移除之前
        /// </summary>
        UnitRemoveEvent,

        UnitAddItem,
        UnitRemoveItem,
        UnitSwapItemLoc,
        UnitItemUpdateCharges,
        UnitAfterRemoveItem,
        OnSendSkillShakingEvent,
        HideOtherInfoPanel,
        UnitSkillLevelUp,


        UnitReborn,

        UnitItemUpdate,

        RecvS2C_StartPickHero,
        UnitDead,
		
        PlayerSignalComponentUpdate,

        UnitIntoGrass,
        UnitExitGrass,
        UnitVisibleTypeChange,

        CustomProfileReceive,
        SelectHero,
        UnitBuffDispose,

        SkillPanelDown,
        Herokilled,
        UnitHited,
        QualityLevelChange,
        BreakChannelSkill,
        UnitRemove,
        SkillShakingError,

        PortalChangeShowSystemNoticeRun,
        HeroDeathShowSystemNoticeRun,
        UnitRemoveShowSystemNoticeRun,
        OutputToChatNodeRun,
        EffectFactory,
        LoadingFinishStartGame,
		LoadingFinishStartGame_Map4C,

		PortalStateChange,
        HPVisibleChange,
        PlayerNameVisibleChange,
        ShopItemButtonOnHover,
        OtherPnaelItemBtnOnHover,
        SettlementItemBtnOnHover,
        ItemShopItemButtonOnHover,
        TabItemButtonOnHover,
        EquippedItemButtonOnHover,
        BagItemButtonOnHover,
        CreateEffectInSmallMapNode,
        ActorDetailInfoSettingBtnOnUp,
        ChangeSkillsIconEffectStateNodeRun,
        HallTipsUICloseBtnClickToHall,
        LoginUIRegisterBtnOnClick,
        LobbyBottomTaskBtnOnUp,
        LobbyBottomMessageBtnOnUp,
        ShowKillReport,
        KillReportEvent,
        //收到服务器封包
        RecvS2C_ActorDetailInfo,
        RecvS2C_GameOverJieSuan,
        RecvS2C_UnitReborn,
        RecvS2C_UpdateRoomInfo,
        RecvS2C_QuitGroup,
        RecvS2C_DownloadMapProcess,
        RecvS2C_JoinGroup,
        RecvS2C_PlatformBuff,
        RecvS2C_RequestSurrender,
        RecvS2C_UnitDieReborn,
        RecvS2C_PlayerSelectHero,
        RecvS2C_RegisterAccount,
        RecvS2C_StartLoading,
        RecvS2C_SkillBreakChannel,
        RecvS2C_SkillEnterChannel,
        RecvS2C_LoginGateSucceedNameSummoner,
        RecvS2C_LoginGateSucceedReconnectGame,
        RecvS2C_ReconnectBattleServer,
        RecvS2C_MapState,
        ChangeToLobbyFinish,
        ChangeToLoginFinish,
        InitSceneStartChangeToLoginFinish,
        InitSceneStartLoadBundleFinish,
        ChangeNameSucceed,
        FriendQueryPlayerFinish,
        FriendsCommonMenuPersonalInfoButtonUp,
        FriendsMenuFriendInfoButtonClick,
        FriendsMenuUIButton1Click,
        MainChatManagerViewInfoButtonClick,
        NewLobbyTopPanelHeadButtonClick,
        SettlementUIStatisticsBtnClick,
        LobbyTopBuffIconOnHover,
        SettlementExpCardBtnOnHover,
        SettlementGoldCardBtnOnHover,
        NewLobbyLogoButtonUp,
        NewLobbyHomeButtonUp,
        FriendsCommonMenuUIMenuBtnOnUp,
        RecvS2C_StartGame,
        RecvS2C_GetFriendList,
        RecvS2C_NotifyDeleteFriend,
        RecvS2C_UpdateFriendStatus,
        RecvS2C_ModifyFaction,
        RecvS2C_UnitDestroy,
        LoabbyUIOnShowPanel,
        LoabbyUIBackToPreviousOnShowPanel,
        LoabbyUIOnShowMainPanel,
        PlayerLeaveRoom,
        PlayMatchingUIReturnLobbyBtnOnClick,
        LobbyUIStartGameBtnOnClick,
        SettlementUIAddFriendBtnOnHover,
        SettlementUILikeBtnOnHover,
        SettlementUITagsEnumBtnOnHover,
        SettlementUIBlacklistBtnOnHover,
        SettlementUIReportBtnOnHover,
        OtherPanelADBtnOnHover,
        OtherPanelMasteryBtnOnHover,
        OtherPanelAttackSpeedBtnOnHover,
        OtherPanelSpeedBtnOnHover,
        OtherPanelADDefanceBtnOnHover,
        OtherPanelAPDefanceBtnOnHover,
        OtherPanelCDRatioBtnOnHover,
        OtherPanelPhysicalCritPercentBtnOnHover,
        MyNumericUIAttackDamageBtnOnHover,
        MyNumericUIMasteryBtnOnHover,
        MyNumericUIPhysicalArmorBtnOnHover,
        MyNumericUIMagicArmorBtnOnHover,
        MyNumericUIAttackSpeedBtnOnHover,
        MyNumericUICDRatioBtnOnHover,
        MyNumericUIPhysicalCritPercentBtnOnHover,
        MyNumericUIMoveSpeedBtnOnHover,
        BuffIconOnHoverByBuffPanelUI,
        BuffIconOnHoverByBuffIconUI,
        RemoveBuffSucceedByOtherPanelUI,
        RemoveBuffSucceedByBuffPanelUI,
        BuffEffectSlientEnter,
        BuffEffectSlientExit,
        DisplayItemShopNodeRun,
        UpdateShopUINodeRun,
        SkillPanelGoldBtnOnClick,
        SkillPanelShopBtnOnClick,
        SurrenderBtnActive,
        GameSettingUIToggleChanged,
        HotKeySettingButtonOnConfirm,
        SettingPanelConfirmBtnOnClick,
        UIOtherPanelRefreshBuff,
        WildIconVisible,
        CreateEffectInSmallMapNodeRun,
        MoveCameraLimitToBorder,
        MiniIconVisible,
        StartCastSkill,
        HallTipsUICloseBtnClickToLogin,
		MapBundleDownloaderABundle,
		LoginBundleDownloaderABundle,
        MessageHandleFriendRequest,
        MessageHandleGroupInviteRequest,
        MessageGroupRefresh,
        MessageGroupItemClearMsg,
        MessageGroupItemClearBtnOnUp,
        MessageDetailItemAcceptBtnOnUp,
        MessageDetailItemRefuseBtnOnUp,
        MessagePopPanelAcceptBtnOnUp,
        MessagePopPanelRefuseBtnOnUp,
        MessageTeamPanelAcceptBtnOnUp,
        MessageTeamPanelRefuseBtnOnUp,
        MessageTeamItemAcceptBtnOnUp,
        MessageTeamItemRefuseBtnOnUp,
        //behavior tree editor event

        // BehaviorTreeEvent_RunTree,
        BehaviorTreeRunTreeEvent,
        BehaviorTreeOpenEditor,
        BehaviorTreeClickNode,
        BehaviorTreeAfterChangeNodeType,
        BehaviorTreeCreateNode,
        BehaviorTreePropertyDesignerNewCreateClick,
        BehaviorTreeMouseInNode,
        BehaviorTreeConnectState,
        BehaviorTreeReplaceClick,
        BehaviorTreeRightDesignerDrag,
        //
        ShowSystemNoticeRun,

		LogError,
        BuffEffectWindowEditor,
        BuffEffectBehaviorTreeEditor,
        BehaviourTreeEditor,
        SkillActionWindow,
        SkillEffectWindowEditor,
    }
}