Import('env')

thread_env = env.Clone()

thread_env.Append(LIBS=[
	'boost_thread'
])

thread_src = [
	'ThreadPool.cc',
]

thread_lib = thread_env.StaticLibrary('thread', thread_src)

thread_env.Append(LIBS=thread_lib)

thread_env.Test('ThreadPoolTest', 'ThreadPoolTest.cc')
