Import('env')

thread_env = env.Clone()

thread_env.Append(LIBS=[
	'boost_thread'
])

thread_src = [
	'thread_pool.cc',
]

thread_lib = thread_env.StaticLibrary('thread', thread_src)

thread_env.Append(LIBS=thread_lib)

thread_env.Program('thread_pool_test.cc')
