Import('env')

net_env = env.Clone()

net_src = [
	'asyn_server.cc',
	'connection.cc',
]

net_lib = net_env.StaticLibrary('net', net_src)

net_env.Append(LIBS=net_lib)

net_env.Program('asyn_server_test.cc')
net_env.Program('connection_test.cc')
