//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;



namespace ET
{

public sealed partial class AttributeInfoRaw :  Bright.Config.BeanBase 
{
    public AttributeInfoRaw(ByteBuf _buf) 
    {
        NumericType = (NumericType)_buf.ReadInt();
        Value = _buf.ReadFloat();
        PostInit();
    }

    public static AttributeInfoRaw DeserializeAttributeInfoRaw(ByteBuf _buf)
    {
        return new AttributeInfoRaw(_buf);
    }

    /// <summary>
    /// 数值类型
    /// </summary>
    public NumericType NumericType { get; private set; }
    /// <summary>
    /// 数值
    /// </summary>
    public float Value { get; private set; }

    public const int __ID__ = 1531821694;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "NumericType:" + NumericType + ","
        + "Value:" + Value + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}
