//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ET
{
    /// <summary>
    /// 覆盖类型
    /// </summary>
    public enum BuffOverrideType
    {
        /// <summary>
        /// 无
        /// </summary>
        None = 0,
        /// <summary>
        /// 叠加
        /// </summary>
        Addition = 1,
        /// <summary>
        /// 覆盖
        /// </summary>
        Replace = 2,
        /// <summary>
        /// 延长
        /// </summary>
        Extend = 3,
    }
}
