//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ET
{
    public enum ConsumeType
    {
        /// <summary>
        /// 无
        /// </summary>
        None = 0,
        /// <summary>
        /// 物品
        /// </summary>
        Item = 1,
        /// <summary>
        /// 行动点
        /// </summary>
        ActionPoint = 2,
        /// <summary>
        /// 属性
        /// </summary>
        Attribute = 3,
    }
}
