//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ET
{
    public enum ErrorCode
    {
        Success = 0,
        Fail = 200002,
        NetworkError = 200003,
        RequestRepeatedly = 200004,
        RequestSceneTypeError = 200005,
        LoginInfoError = 200011,
        AccountNameBlackList = 200012,
        AccountNameEmpty = 200013,
        PasswordError = 200014,
        TokenError = 200015,
        RoleNameNull = 200016,
        RoleNameSame = 200017,
        RoleNameExist = 200018,
        ConnectGateKeyError = 200019,
        OtherAccountLoginError = 200020,
        SessionPlayerError = 200021,
        NonePlayerError = 200022,
        PlayerSessionError = 200023,
        SessionStateError = 200024,
        EnterGameError = 200025,
        ReEnterGameError = 200026,
        ReEnterGameError2 = 200027,
        StopAI = 200101,
    }
}
