//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ET
{
    public enum FGUIType
    {
        /// <summary>
        /// -1
        /// </summary>
        None = 0,
        /// <summary>
        /// 0
        /// </summary>
        Default = 1,
        /// <summary>
        /// 1
        /// </summary>
        Background = 2,
        /// <summary>
        /// 2
        /// </summary>
        Loading = 3,
        /// <summary>
        /// 3
        /// </summary>
        Lobby = 4,
        /// <summary>
        /// 4
        /// </summary>
        Login = 5,
        /// <summary>
        /// 5
        /// </summary>
        Register = 6,
        /// <summary>
        /// 6
        /// </summary>
        HomePage = 7,
        /// <summary>
        /// 7
        /// </summary>
        Hero = 8,
        /// <summary>
        /// 8
        /// </summary>
        Adventure = 9,
        /// <summary>
        /// 9
        /// </summary>
        Arena = 10,
        /// <summary>
        /// 10
        /// </summary>
        Battle = 11,
        /// <summary>
        /// 11
        /// </summary>
        Pub = 12,
        /// <summary>
        /// 12
        /// </summary>
        WareHouse = 13,
        /// <summary>
        /// 13
        /// </summary>
        TreeConsole = 14,
        /// <summary>
        /// 14
        /// </summary>
        MessageBox = 15,
        /// <summary>
        /// 15
        /// </summary>
        TextTips = 16,
        /// <summary>
        /// 90
        /// </summary>
        Test = 17,
    }
}
