//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;



namespace ET
{

public sealed partial class SkillPickTargetWeights :  Bright.Config.BeanBase 
{
    public SkillPickTargetWeights(ByteBuf _buf) 
    {
        Id = (SkillRange)_buf.ReadInt();
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);PickWeightInfos = new System.Collections.Generic.List<PickWeightInfo>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { PickWeightInfo _e0;  _e0 = PickWeightInfo.DeserializePickWeightInfo(_buf); PickWeightInfos.Add(_e0);}}
        PostInit();
    }

    public static SkillPickTargetWeights DeserializeSkillPickTargetWeights(ByteBuf _buf)
    {
        return new SkillPickTargetWeights(_buf);
    }

    /// <summary>
    /// 攻击距离
    /// </summary>
    public SkillRange Id { get; private set; }
    /// <summary>
    /// 各位置的权重
    /// </summary>
    public System.Collections.Generic.List<PickWeightInfo> PickWeightInfos { get; private set; }

    public const int __ID__ = 2010650968;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var _e in PickWeightInfos) { _e?.Resolve(_tables); }
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var _e in PickWeightInfos) { _e?.TranslateText(translator); }
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "PickWeightInfos:" + Bright.Common.StringUtil.CollectionToString(PickWeightInfos) + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}
