//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;

namespace ET
{
   
public partial class TbContainer
{
    private readonly Dictionary<int, ContainerConfig> _dataMap;
    private readonly List<ContainerConfig> _dataList;
    
    public TbContainer(ByteBuf _buf)
    {
        _dataMap = new Dictionary<int, ContainerConfig>();
        _dataList = new List<ContainerConfig>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            ContainerConfig _v;
            _v = ContainerConfig.DeserializeContainerConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
        PostInit();
    }

    public Dictionary<int, ContainerConfig> DataMap => _dataMap;
    public List<ContainerConfig> DataList => _dataList;

    public ContainerConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public ContainerConfig Get(int key) => _dataMap[key];
    public ContainerConfig this[int key] => _dataMap[key];

    public void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}