
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{

    [Config]
    public partial class NumericDemoConfigCategory : Singleton<NumericDemoConfigCategory>, ILubanConfig
    {
        private readonly Dictionary<int, NumericDemoConfig> _dataMap;
        private readonly List<NumericDemoConfig> _dataList;
        
        public NumericDemoConfigCategory(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, NumericDemoConfig>();
            _dataList = new List<NumericDemoConfig>();
            
            for(int n = _buf.ReadSize() ; n > 0 ; --n)
            {
                NumericDemoConfig _v;
                _v = NumericDemoConfig.DeserializeNumericDemoConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }
            EndInit();
        }

        public Dictionary<int, NumericDemoConfig> GetAll() => _dataMap;
        public Dictionary<int, NumericDemoConfig> DataMap => _dataMap;
        public List<NumericDemoConfig> DataList => _dataList;

        public NumericDemoConfig GetOrDefault(int key) => _dataMap.GetValueOrDefault(key);

        public NumericDemoConfig Get(int key)
        {
            if (_dataMap.TryGetValue(key,out var v))
            {
                return v;
            }
            LubanLog.Error(this,key);
            return default;
        }

        public void ResolveRef()
        {
            foreach(var _v in _dataList)
            {
                _v.ResolveRef();
            }
            EndRef();
        }


        partial void EndRef();
    }

}

