//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;



namespace ET.BuffVoidCaster
{

public sealed partial class None :  Base 
{
    public None(ByteBuf _buf)  : base(_buf) 
    {
        PostInit();
    }

    public static None DeserializeNone(ByteBuf _buf)
    {
        return new BuffVoidCaster.None(_buf);
    }


    public const int __ID__ = -1394027341;
    public override int GetTypeId() => __ID__;

    public override void Resolve(Dictionary<string, object> _tables)
    {
        base.Resolve(_tables);
        PostResolve();
    }

    public override void TranslateText(System.Func<string, string, string> translator)
    {
        base.TranslateText(translator);
    }

    public override string ToString()
    {
        return "{ "
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}
