
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace ET
{
    [EnableClass]
    public sealed partial class NumericDemoConfig : Luban.BeanBase
    {
        public NumericDemoConfig(ByteBuf _buf) 
        {
            Id = _buf.ReadInt();
            {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);Numeric = new System.Collections.Generic.Dictionary<ENumericType, long>(n0 * 3 / 2);for(var i0 = 0 ; i0 < n0 ; i0++) { ENumericType _k0;  _k0 = (ENumericType)_buf.ReadInt(); long _v0;  _v0 = _buf.ReadLong();     Numeric.Add(_k0, _v0);}}

            EndInit();
        }

        public static NumericDemoConfig DeserializeNumericDemoConfig(ByteBuf _buf)
        {
            return new NumericDemoConfig(_buf);
        }

        /// <summary>
        /// id
        /// </summary>
        public readonly int Id;
        /// <summary>
        /// k
        /// </summary>
        public readonly System.Collections.Generic.Dictionary<ENumericType, long> Numeric;
    
        public const int __ID__ = 47825362;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            EndRef();
        }

        public override string ToString()
        {
            return "{ "
            + "id:" + Id + ","
            + "numeric:" + Luban.StringUtil.CollectionToString(Numeric) + ","
            + "}";
        }

        partial void EndRef();
    }

}

