//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modules.Robot
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_challenge_activity_schedule
    {
        public string activity_id { get; set; }
        public System.DateTime elect_from_time { get; set; }
        public System.DateTime elect_to_time { get; set; }
        public System.DateTime guess_from_time { get; set; }
        public System.DateTime guess_to_time { get; set; }
        public System.DateTime reward_from_time { get; set; }
        public System.DateTime reward_to_time { get; set; }
        public System.DateTime create_time { get; set; }
        public System.DateTime modify_time { get; set; }
    }
}
