//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modules.Robot
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_character
    {
        public decimal character_guid { get; set; }
        public int general_class { get; set; }
        public string character_name { get; set; }
        public int sex { get; set; }
        public decimal account_id { get; set; }
        public string playing_map_server_key { get; set; }
        public decimal group_guid { get; set; }
        public decimal room_guid { get; set; }
        public int general_ghost { get; set; }
        public int kingdom { get; set; }
        public string create_ip { get; set; }
        public int area_id { get; set; }
        public string account { get; set; }
        public int default_display_id { get; set; }
        public int selected_title_type { get; set; }
        public long last_login_time { get; set; }
        public string login_ip { get; set; }
        public bool is_first_login { get; set; }
        public bool has_newly_mail { get; set; }
        public string location { get; set; }
        public long history_silver { get; set; }
        public long history_charge_gold { get; set; }
        public long history_free_gold { get; set; }
        public int rank_bonus_title_id { get; set; }
        public System.DateTime create_time { get; set; }
        public System.DateTime modify_time { get; set; }
        public int recent_flee_buff_id { get; set; }
        public int add_buff_yday { get; set; }
        public sbyte need_rename { get; set; }
        public bool can_gain_active_code_item { get; set; }
        public long total_online_seconds { get; set; }
        public string city_server_name { get; set; }
        public string last_login_realtime { get; set; }
        public int anti_addiction_online_time { get; set; }
        public int anti_addiction_offline_time { get; set; }
        public string gs_active_code { get; set; }
        public Nullable<long> ban_login_expired_time { get; set; }
        public Nullable<long> ban_chat_expired_time { get; set; }
        public int pve_equipment_max_strengthen_level { get; set; }
        public int pve_equipment_active_scheme_id { get; set; }
    }
}
