//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modules.Robot
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_charge_list
    {
        public string charge_listid { get; set; }
        public string charge_sn { get; set; }
        public decimal character_guid { get; set; }
        public string account { get; set; }
        public string ip { get; set; }
        public int pay_points { get; set; }
        public int charge_yuanbao { get; set; }
        public int free_yuanbao { get; set; }
        public string url_parameters { get; set; }
        public int charge_state { get; set; }
        public System.DateTime create_time { get; set; }
        public System.DateTime modify_time { get; set; }
        public int retry_times { get; set; }
    }
}
