//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modules.Robot
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_city_task_info
    {
        public decimal task_guid { get; set; }
        public decimal character_guid { get; set; }
        public int task_id { get; set; }
        public int state { get; set; }
        public decimal finish_timestamp { get; set; }
        public decimal accept_time { get; set; }
        public System.DateTime create_time { get; set; }
        public System.DateTime modify_time { get; set; }
    }
}
