//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modules.Robot
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_hero_color_scheme
    {
        public decimal character_guid { get; set; }
        public int hero_id { get; set; }
        public int color_scheme_id { get; set; }
        public long color1 { get; set; }
        public long color2 { get; set; }
        public long color3 { get; set; }
        public long color4 { get; set; }
        public long color5 { get; set; }
        public System.DateTime create_time { get; set; }
        public System.DateTime modify_time { get; set; }
    }
}
