//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modules.Robot
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_map_play_info
    {
        public decimal character_guid { get; set; }
        public string map_type { get; set; }
        public int play_count { get; set; }
        public int win_count { get; set; }
        public decimal last_play_date { get; set; }
        public decimal total_play_time { get; set; }
        public int today_play_time { get; set; }
        public int current_level { get; set; }
        public int max_score { get; set; }
        public int kill_boss_count { get; set; }
        public long kill_hostile_soldier { get; set; }
        public int max_total_damage { get; set; }
        public int max_total_suffer_damage { get; set; }
        public int max_total_heal { get; set; }
        public System.DateTime create_time { get; set; }
        public System.DateTime modify_time { get; set; }
    }
}
