//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modules.Robot
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_rune_scheme
    {
        public decimal character_guid { get; set; }
        public int scheme_id { get; set; }
        public string scheme_name { get; set; }
        public decimal slot0_item_guid { get; set; }
        public decimal slot1_item_guid { get; set; }
        public decimal slot2_item_guid { get; set; }
        public decimal slot3_item_guid { get; set; }
        public decimal slot4_item_guid { get; set; }
        public decimal slot5_item_guid { get; set; }
        public decimal slot6_item_guid { get; set; }
        public decimal slot7_item_guid { get; set; }
        public decimal slot8_item_guid { get; set; }
        public decimal slot9_item_guid { get; set; }
        public decimal slot10_item_guid { get; set; }
        public decimal slot11_item_guid { get; set; }
        public decimal slot12_item_guid { get; set; }
        public decimal slot13_item_guid { get; set; }
        public decimal slot14_item_guid { get; set; }
        public Nullable<System.DateTime> create_time { get; set; }
        public Nullable<System.DateTime> modify_time { get; set; }
    }
}
