//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace ET
{

public sealed partial class StartMachineConfig: Bright.Config.BeanBase
{
    public StartMachineConfig(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        InnerIP = _buf.ReadString();
        OuterIP = _buf.ReadString();
        WatcherPort = _buf.ReadString();
        PostInit();
    }

    public static StartMachineConfig DeserializeStartMachineConfig(ByteBuf _buf)
    {
        return new StartMachineConfig(_buf);
    }

    /// <summary>
    /// 这是id
    /// </summary>
    public int Id { get; private set; }
    /// <summary>
    /// 内网地址
    /// </summary>
    public string InnerIP { get; private set; }
    /// <summary>
    /// 外网地址
    /// </summary>
    public string OuterIP { get; private set; }
    /// <summary>
    /// 守护进程端口
    /// </summary>
    public string WatcherPort { get; private set; }

    public const int __ID__ = 1628109127;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, IConfigSingleton> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "InnerIP:" + InnerIP + ","
        + "OuterIP:" + OuterIP + ","
        + "WatcherPort:" + WatcherPort + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}