//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;



namespace ET.AICondition
{

public sealed partial class PickSingle :  Base 
{
    public PickSingle(ByteBuf _buf)  : base(_buf) 
    {
        TargetTeam = (PickTeam)_buf.ReadInt();
        PostInit();
    }

    public static PickSingle DeserializePickSingle(ByteBuf _buf)
    {
        return new AICondition.PickSingle(_buf);
    }

    public PickTeam TargetTeam { get; private set; }

    public const int __ID__ = -499250460;
    public override int GetTypeId() => __ID__;

    public override void Resolve(Dictionary<string, object> _tables)
    {
        base.Resolve(_tables);
        PostResolve();
    }

    public override void TranslateText(System.Func<string, string, string> translator)
    {
        base.TranslateText(translator);
    }

    public override string ToString()
    {
        return "{ "
        + "TargetTeam:" + TargetTeam + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}
