//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;



namespace ET.AICondition
{

public sealed partial class PickMulti :  Base 
{
    public PickMulti(ByteBuf _buf)  : base(_buf) 
    {
        TargetTeam = (PickTeam)_buf.ReadInt();
        TargetNum = _buf.ReadInt();
        PostInit();
    }

    public static PickMulti DeserializePickMulti(ByteBuf _buf)
    {
        return new AICondition.PickMulti(_buf);
    }

    public PickTeam TargetTeam { get; private set; }
    /// <summary>
    /// 目标数量，-1就是全部
    /// </summary>
    public int TargetNum { get; private set; }

    public const int __ID__ = 1918372637;
    public override int GetTypeId() => __ID__;

    public override void Resolve(Dictionary<string, object> _tables)
    {
        base.Resolve(_tables);
        PostResolve();
    }

    public override void TranslateText(System.Func<string, string, string> translator)
    {
        base.TranslateText(translator);
    }

    public override string ToString()
    {
        return "{ "
        + "TargetTeam:" + TargetTeam + ","
        + "TargetNum:" + TargetNum + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}
