FIND_PATH(GTEST_INCLUDE_DIR gtest/gtest.h)

FIND_LIBRARY(GTEST_LIBRARY NAMES gtest
             DOC "The Google Gtest Library"
             )

MARK_AS_ADVANCED(GTEST_INCLUDE_DIR GTEST_LIBRARY)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(GTEST DEFAULT_MSG GTEST_LIBRARY GTEST_INCLUDE_DIR)

IF(GTEST_FOUND)
    SET(GTEST_INCLUDE_DIRS ${GTEST_INCLUDE_DIR})
    SET(GTEST_LIBRARIES    ${GTEST_LIBRARY})
ENDIF()