FIND_PATH(GFLAGS_INCLUDE_DIR gflags/gflags.h)

# Google's provided vcproj files generate libraries with a "lib"
# prefix on Windows
IF(WIN32)
    SET(GFLAGS_ORIG_FIND_LIBRARY_PREFIXES "${CMAKE_FIND_LIBRARY_PREFIXES}")
    SET(CMAKE_FIND_LIBRARY_PREFIXES "lib" "")
ENDIF()

FIND_LIBRARY(GFLAGS_LIBRARY NAMES gflags
             DOC "The Google Gflags Library"
             )

MARK_AS_ADVANCED(GFLAGS_INCLUDE_DIR GFLAGS_LIBRARY)

# Restore original find library prefixes
IF(WIN32)
    SET(CMAKE_FIND_LIBRARY_PREFIXES "${GFLAGS_ORIG_FIND_LIBRARY_PREFIXES}")
ENDIF()

include(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(GFLAGS DEFAULT_MSG GFLAGS_LIBRARY GFLAGS_INCLUDE_DIR)

IF(GFLAGS_FOUND)
    SET(GFLAGS_INCLUDE_DIRS ${GFLAGS_INCLUDE_DIR})
    SET(GFLAGS_LIBRARIES    ${GFLAGS_LIBRARY})
ENDIF()