
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace ET
{
    [EnableClass]
    public sealed partial class ConditionCheckLevel : ConditionCheckValue
    {
        public ConditionCheckLevel(ByteBuf _buf)  : base(_buf) 
        {
            Level = _buf.ReadInt();

            EndInit();
        }

        public static ConditionCheckLevel DeserializeConditionCheckLevel(ByteBuf _buf)
        {
            return new ConditionCheckLevel(_buf);
        }

        /// <summary>
        /// 检查等级
        /// </summary>
        public readonly int Level;
    
        public const int __ID__ = -2093853001;
        public override int GetTypeId() => __ID__;

        public override void ResolveRef()
        {
            base.ResolveRef();
            EndRef();
        }

        public override string ToString()
        {
            return "{ "
            + "level:" + Level + ","
            + "}";
        }

        partial void EndRef();
    }

}

