
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace ET
{
    [EnableClass]
    public sealed partial class ConditionCheckData : Luban.BeanBase
    {
        public ConditionCheckData(ByteBuf _buf) 
        {
            Id = (EConditionId)_buf.ReadInt();
            Id_Ref = null;
            CheckValue = ConditionCheckValue.DeserializeConditionCheckValue(_buf);

            EndInit();
        }

        public static ConditionCheckData DeserializeConditionCheckData(ByteBuf _buf)
        {
            return new ConditionCheckData(_buf);
        }

        /// <summary>
        /// 条件表ID
        /// </summary>
        public readonly EConditionId Id;
        public ConditionConfig Id_Ref;
        /// <summary>
        /// 检查参数值
        /// </summary>
        public readonly ConditionCheckValue CheckValue;
    
        public const int __ID__ = 1733329431;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            Id_Ref = ConditionConfigCategory.Instance.GetOrDefault(Id);
            CheckValue?.ResolveRef();
            EndRef();
        }

        public override string ToString()
        {
            return "{ "
            + "id:" + Id + ","
            + "checkValue:" + CheckValue + ","
            + "}";
        }

        partial void EndRef();
    }

}

