
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace ET
{
    /// <summary>
    /// 比较参数基类
    /// </summary>
    [EnableClass]
    public abstract partial class ConditionCheckValue : Luban.BeanBase
    {
        public ConditionCheckValue(ByteBuf _buf) 
        {

            EndInit();
        }

        public static ConditionCheckValue DeserializeConditionCheckValue(ByteBuf _buf)
        {
            switch (_buf.ReadInt())
            {
                case ConditionCheckLevel.__ID__: return new ConditionCheckLevel(_buf);
                default: throw new SerializationException();
            }
        }

    

        public virtual void ResolveRef()
        {
            EndRef();
        }

        public override string ToString()
        {
            return "{ "
            + "}";
        }

        partial void EndRef();
    }

}

