Import('env')

python_env = env.Clone()

python_env.Append(LIBS=[
	"boost_python",
	"python2.6",
])

python_env.Append(CPPPATH=[
	"/usr/include/python2.6"
])

python_env.Test("PythonInitTest", "PythonInitTest.cc")
