
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace ET
{
    [EnableClass]
    public sealed partial class NumericLocalizationConfig : Luban.BeanBase
    {
        public NumericLocalizationConfig(ByteBuf _buf) 
        {
            Id = (ENumericType)_buf.ReadInt();
            Localization = _buf.ReadString();
            Describe = _buf.ReadString();
            Icon = _buf.ReadString();
            Specifier = _buf.ReadString();

            EndInit();
        }

        public static NumericLocalizationConfig DeserializeNumericLocalizationConfig(ByteBuf _buf)
        {
            return new NumericLocalizationConfig(_buf);
        }

        /// <summary>
        /// 数值id
        /// </summary>
        public readonly ENumericType Id;
        /// <summary>
        /// 本地化(先直接用 以后接多语言本地化)
        /// </summary>
        public readonly string Localization;
        /// <summary>
        /// 描述
        /// </summary>
        public readonly string Describe;
        /// <summary>
        /// 图标
        /// </summary>
        public readonly string Icon;
        /// <summary>
        /// 转换说明符
        /// </summary>
        public readonly string Specifier;
    
        public const int __ID__ = -765489912;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            EndRef();
        }

        public override string ToString()
        {
            return "{ "
            + "id:" + Id + ","
            + "localization:" + Localization + ","
            + "describe:" + Describe + ","
            + "icon:" + Icon + ","
            + "specifier:" + Specifier + ","
            + "}";
        }

        partial void EndRef();
    }

}

