
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace ET
{
    [EnableClass]
    public sealed partial class NumericValueCheckConfig : Luban.BeanBase
    {
        public NumericValueCheckConfig(ByteBuf _buf) 
        {
            Id = (ENumericType)_buf.ReadInt();
            Check = (ENumericValueType)_buf.ReadInt();
            Alias = _buf.ReadString();
            Desc = _buf.ReadString();
            NotGrow = _buf.ReadBool();

            EndInit();
        }

        public static NumericValueCheckConfig DeserializeNumericValueCheckConfig(ByteBuf _buf)
        {
            return new NumericValueCheckConfig(_buf);
        }

        public readonly ENumericType Id;
        public readonly ENumericValueType Check;
        public readonly string Alias;
        public readonly string Desc;
        public readonly bool NotGrow;
    
        public const int __ID__ = -622042810;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            EndRef();
        }

        public override string ToString()
        {
            return "{ "
            + "id:" + Id + ","
            + "check:" + Check + ","
            + "alias:" + Alias + ","
            + "desc:" + Desc + ","
            + "notGrow:" + NotGrow + ","
            + "}";
        }

        partial void EndRef();
    }

}

