//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataCenter
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_account
    {
        public string account { get; set; }
        public Nullable<decimal> account_guid { get; set; }
        public byte[] sessionkey { get; set; }
        public string v { get; set; }
        public string s { get; set; }
        public string active_code { get; set; }
        public Nullable<bool> active_code_used { get; set; }
        public Nullable<decimal> first_char_guid { get; set; }
        public Nullable<System.DateTime> create_time { get; set; }
        public Nullable<System.DateTime> modify_time { get; set; }
        public int gm_level { get; set; }
    }
}
