//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataCenter
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_account_login_auth_response_cookie
    {
        public string account { get; set; }
        public string aid { get; set; }
        public string ssn { get; set; }
        public string gamepoint { get; set; }
        public string balance { get; set; }
        public string sn { get; set; }
        public string user_type { get; set; }
        public string otpstat { get; set; }
        public string otpuptime { get; set; }
        public string infosafe { get; set; }
        public string phonestat { get; set; }
        public string ppcstat { get; set; }
        public string ppccoord { get; set; }
        public string mppstat { get; set; }
        public string rnstat { get; set; }
        public string regtime { get; set; }
        public string mobileno { get; set; }
        public string need_activate_game { get; set; }
        public string game_flag { get; set; }
        public string deactivated { get; set; }
        public string uidcount { get; set; }
        public string newtm { get; set; }
        public string vipstatus { get; set; }
        public string is_vip_phone_trusty { get; set; }
        public string is_vip_addr_trusty { get; set; }
        public string real_name_flag { get; set; }
        public string mobileisactivated { get; set; }
        public string secu_info_ready { get; set; }
        public string secu_info_pin_ma { get; set; }
        public string secu_info_id_num { get; set; }
        public string id_num { get; set; }
        public Nullable<System.DateTime> create_time { get; set; }
        public Nullable<System.DateTime> modify_time { get; set; }
    }
}
