//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataCenter
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_auction_item
    {
        public decimal item_guid { get; set; }
        public bool is_deleted { get; set; }
        public decimal seller_guid { get; set; }
        public string seller_name { get; set; }
        public string seller_ip { get; set; }
        public short auction_class { get; set; }
        public string item_name { get; set; }
        public int item_id { get; set; }
        public short assets_type { get; set; }
        public int deposit { get; set; }
        public int sum_price { get; set; }
        public float unit_price { get; set; }
        public System.DateTime expire_time { get; set; }
        public decimal tran_guid { get; set; }
        public System.DateTime create_time { get; set; }
        public System.DateTime modify_time { get; set; }
    }
}
