//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataCenter
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_character_item
    {
        public decimal item_guid { get; set; }
        public decimal character_guid { get; set; }
        public int item_id { get; set; }
        public int slot { get; set; }
        public int item_count { get; set; }
        public System.DateTime create_time { get; set; }
        public System.DateTime modify_time { get; set; }
        public int source { get; set; }
        public bool is_bound { get; set; }
        public int location { get; set; }
        public byte[] attributes { get; set; }
        public System.DateTime buy_time { get; set; }
        public System.DateTime expire_time { get; set; }
        public int buy_type { get; set; }
        public int pay_type { get; set; }
        public int pay_yuanbao { get; set; }
        public int free_yuanbao { get; set; }
        public int reiki_count { get; set; }
        public int durability_count { get; set; }
        public int recast_count { get; set; }
    }
}
