//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataCenter
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_character_appearance
    {
        public decimal character_guid { get; set; }
        public int appearance_type { get; set; }
        public decimal headdress { get; set; }
        public decimal wing { get; set; }
        public decimal clothes { get; set; }
        public decimal weapon { get; set; }
        public decimal magic_weapon { get; set; }
        public decimal mounts { get; set; }
        public decimal face { get; set; }
        public int riding_status { get; set; }
        public long color1 { get; set; }
        public long color2 { get; set; }
        public long color3 { get; set; }
        public long color4 { get; set; }
        public long color5 { get; set; }
        public int default_visual { get; set; }
        public int default_face { get; set; }
        public int default_headdress { get; set; }
        public int color_scheme_id { get; set; }
        public System.DateTime create_time { get; set; }
        public System.DateTime modify_time { get; set; }
    }
}
