//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataCenter
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_challenge_activity
    {
        public string activity_id { get; set; }
        public int activity_status { get; set; }
        public System.DateTime start_time { get; set; }
        public decimal battle_id { get; set; }
        public bool challenger_win { get; set; }
        public int kfz_best_hero { get; set; }
        public Nullable<System.DateTime> game_over_time { get; set; }
        public long challenger_win_bet { get; set; }
        public long challenger_lose_bet { get; set; }
        public System.DateTime create_time { get; set; }
        public System.DateTime modify_time { get; set; }
    }
}
