//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataCenter
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_character_options
    {
        public decimal character_guid { get; set; }
        public string rune_not_show_binding_tips { get; set; }
        public System.DateTime create_time { get; set; }
        public System.DateTime modify_time { get; set; }
    }
}
