//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataCenter
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_game_info
    {
        public decimal character_guid { get; set; }
        public string character_name { get; set; }
        public int register_area { get; set; }
        public int character_level { get; set; }
        public int experience { get; set; }
        public long experience_uptime { get; set; }
        public int stage_score { get; set; }
        public long stage_score_uptime { get; set; }
        public int win_count { get; set; }
        public int lose_count { get; set; }
        public int flee_count { get; set; }
        public int max_kill_games { get; set; }
        public int max_assist_games { get; set; }
        public int max_destroy_hostile_towner_games { get; set; }
        public int first_blood_games { get; set; }
        public int max_money_games { get; set; }
        public int kill_boss_count { get; set; }
        public long kill_boss_count_uptime { get; set; }
        public int max_money { get; set; }
        public int max_assist { get; set; }
        public int max_kill { get; set; }
        public int exploit_value { get; set; }
        public int pass_level_count { get; set; }
        public int lose_level_count { get; set; }
        public int get_s_count { get; set; }
        public long last_level_up_time { get; set; }
        public double mean { get; set; }
        public double deviation { get; set; }
        public decimal total_kill_boss_number { get; set; }
        public decimal played_time { get; set; }
        public decimal in_city_time { get; set; }
        public decimal in_match_time { get; set; }
        public decimal in_room_time { get; set; }
        public int arena_match_score { get; set; }
        public int funny_match_score { get; set; }
        public int good_reputation_count { get; set; }
        public int wujiangshilian_play_time { get; set; }
        public int youzhou_last_play_soldier_count { get; set; }
        public int youzhou_last_play_soldier_level { get; set; }
        public int vip_exp { get; set; }
        public Nullable<int> vip_exp_accumulate { get; set; }
        public Nullable<long> last_vip_exp_up_time { get; set; }
        public System.DateTime create_time { get; set; }
        public System.DateTime modify_time { get; set; }
    }
}
