//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataCenter
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_hero_suggest_equipment
    {
        public decimal character_guid { get; set; }
        public int hero_id { get; set; }
        public int plan_id { get; set; }
        public string plan_description { get; set; }
        public Nullable<int> item_id0 { get; set; }
        public Nullable<int> item_id1 { get; set; }
        public Nullable<int> item_id2 { get; set; }
        public Nullable<int> item_id3 { get; set; }
        public Nullable<int> item_id4 { get; set; }
        public Nullable<int> item_id5 { get; set; }
        public Nullable<bool> is_deleted { get; set; }
        public System.DateTime create_time { get; set; }
        public System.DateTime modify_time { get; set; }
    }
}
