
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{

    [Config]
    public partial class ConditionGroupConfigCategory : Singleton<ConditionGroupConfigCategory>, ILubanConfig
    {
        private readonly Dictionary<EConditionGroupId, ConditionGroupConfig> _dataMap;
        private readonly List<ConditionGroupConfig> _dataList;
        
        public ConditionGroupConfigCategory(ByteBuf _buf)
        {
            _dataMap = new Dictionary<EConditionGroupId, ConditionGroupConfig>();
            _dataList = new List<ConditionGroupConfig>();
            
            for(int n = _buf.ReadSize() ; n > 0 ; --n)
            {
                ConditionGroupConfig _v;
                _v = ConditionGroupConfig.DeserializeConditionGroupConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }
            EndInit();
        }

        public Dictionary<EConditionGroupId, ConditionGroupConfig> GetAll() => _dataMap;
        public Dictionary<EConditionGroupId, ConditionGroupConfig> DataMap => _dataMap;
        public List<ConditionGroupConfig> DataList => _dataList;

        public ConditionGroupConfig GetOrDefault(EConditionGroupId key) => _dataMap.GetValueOrDefault(key);

        public ConditionGroupConfig Get(EConditionGroupId key)
        {
            if (_dataMap.TryGetValue(key,out var v))
            {
                return v;
            }
            LubanLog.Error(this,key);
            return default;
        }

        public void ResolveRef()
        {
            foreach(var _v in _dataList)
            {
                _v.ResolveRef();
            }
            EndRef();
        }


        partial void EndRef();
    }

}

