//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;

namespace ET.StartServer
{
   
public partial class TbStartProcess
{
    private readonly Dictionary<int, StartServer.StartProcess> _dataMap;
    private readonly List<StartServer.StartProcess> _dataList;
    
    public TbStartProcess(ByteBuf _buf)
    {
        _dataMap = new Dictionary<int, StartServer.StartProcess>();
        _dataList = new List<StartServer.StartProcess>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            StartServer.StartProcess _v;
            _v = StartServer.StartProcess.DeserializeStartProcess(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
        PostInit();
    }

    public Dictionary<int, StartServer.StartProcess> DataMap => _dataMap;
    public List<StartServer.StartProcess> DataList => _dataList;

    public StartServer.StartProcess GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public StartServer.StartProcess Get(int key) => _dataMap[key];
    public StartServer.StartProcess this[int key] => _dataMap[key];

    public void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}