//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;



namespace ET.WeightInfo
{

public abstract partial class Base :  Bright.Config.BeanBase 
{
    public Base(ByteBuf _buf) 
    {
        Weight = _buf.ReadInt();
        PostInit();
    }

    public static Base DeserializeBase(ByteBuf _buf)
    {
        switch (_buf.ReadInt())
        {
            case WeightInfo.Hero.__ID__: return new WeightInfo.Hero(_buf);
            case WeightInfo.Equip.__ID__: return new WeightInfo.Equip(_buf);
            case WeightInfo.Pet.__ID__: return new WeightInfo.Pet(_buf);
            default: throw new SerializationException();
        }
    }

    /// <summary>
    /// 权重
    /// </summary>
    public int Weight { get; private set; }


    public virtual void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public virtual void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Weight:" + Weight + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}
