//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;



namespace ET.WeightInfo
{

public sealed partial class Hero :  Base 
{
    public Hero(ByteBuf _buf)  : base(_buf) 
    {
        HeroId = _buf.ReadInt();
        PostInit();
    }

    public static Hero DeserializeHero(ByteBuf _buf)
    {
        return new WeightInfo.Hero(_buf);
    }

    /// <summary>
    /// 英雄id，最好ref一下
    /// </summary>
    public int HeroId { get; private set; }

    public const int __ID__ = 2123215266;
    public override int GetTypeId() => __ID__;

    public override void Resolve(Dictionary<string, object> _tables)
    {
        base.Resolve(_tables);
        PostResolve();
    }

    public override void TranslateText(System.Func<string, string, string> translator)
    {
        base.TranslateText(translator);
    }

    public override string ToString()
    {
        return "{ "
        + "Weight:" + Weight + ","
        + "HeroId:" + HeroId + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}
