
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ET
{ 
    public enum ENumericDefinitionType
    {
        /// <summary>
        /// 无
        /// </summary>
        None = -1,
        /// <summary>
        /// 结果
        /// </summary>
        Result = 0,
        /// <summary>
        /// 基础
        /// </summary>
        Base = 1,
        /// <summary>
        /// 基础增加
        /// </summary>
        Add = 2,
        /// <summary>
        /// 基础百分比
        /// </summary>
        Pct = 3,
        /// <summary>
        /// 最终增加
        /// </summary>
        FinalAdd = 4,
        /// <summary>
        /// 最终百分比
        /// </summary>
        FinalPct = 5,
        /// <summary>
        /// 结果增加
        /// </summary>
        ResultAdd = 6,
    }

} 

