
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{

    [Config]
    public partial class NumericValueCheckConfigCategory : Singleton<NumericValueCheckConfigCategory>, ILubanConfig
    {
        private readonly Dictionary<ENumericType, NumericValueCheckConfig> _dataMap;
        private readonly List<NumericValueCheckConfig> _dataList;
        
        public NumericValueCheckConfigCategory(ByteBuf _buf)
        {
            _dataMap = new Dictionary<ENumericType, NumericValueCheckConfig>();
            _dataList = new List<NumericValueCheckConfig>();
            
            for(int n = _buf.ReadSize() ; n > 0 ; --n)
            {
                NumericValueCheckConfig _v;
                _v = NumericValueCheckConfig.DeserializeNumericValueCheckConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }
            EndInit();
        }

        public Dictionary<ENumericType, NumericValueCheckConfig> GetAll() => _dataMap;
        public Dictionary<ENumericType, NumericValueCheckConfig> DataMap => _dataMap;
        public List<NumericValueCheckConfig> DataList => _dataList;

        public NumericValueCheckConfig GetOrDefault(ENumericType key) => _dataMap.GetValueOrDefault(key);

        public NumericValueCheckConfig Get(ENumericType key)
        {
            if (_dataMap.TryGetValue(key,out var v))
            {
                return v;
            }
            LubanLog.Error(this,key);
            return default;
        }

        public void ResolveRef()
        {
            foreach(var _v in _dataList)
            {
                _v.ResolveRef();
            }
            EndRef();
        }


        partial void EndRef();
    }

}

