
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ET
{ 
    public enum ECompareType
    {
        /// <summary>
        /// 等于
        /// </summary>
        Equal = 1,
        /// <summary>
        /// 不等于
        /// </summary>
        NotEqual = 2,
        /// <summary>
        /// 小于
        /// </summary>
        Less = 3,
        /// <summary>
        /// 小于等于
        /// </summary>
        LessEqual = 4,
        /// <summary>
        /// 大于
        /// </summary>
        Greater = 5,
        /// <summary>
        /// 大于等于
        /// </summary>
        GreaterEqual = 6,
    }

} 

