//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;



namespace ET.BuffCondition
{

/// <summary>
/// 附加时
/// </summary>
public sealed partial class Attach :  Base 
{
    public Attach(ByteBuf _buf)  : base(_buf) 
    {
        PostInit();
    }

    public static Attach DeserializeAttach(ByteBuf _buf)
    {
        return new BuffCondition.Attach(_buf);
    }


    public const int __ID__ = 421458219;
    public override int GetTypeId() => __ID__;

    public override void Resolve(Dictionary<string, object> _tables)
    {
        base.Resolve(_tables);
        PostResolve();
    }

    public override void TranslateText(System.Func<string, string, string> translator)
    {
        base.TranslateText(translator);
    }

    public override string ToString()
    {
        return "{ "
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}
