//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;



namespace ET.BuffVoidCaster
{

public sealed partial class Common :  Base 
{
    public Common(ByteBuf _buf)  : base(_buf) 
    {
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);Attributes = new System.Collections.Generic.List<AttributeInfoRaw>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { AttributeInfoRaw _e0;  _e0 = AttributeInfoRaw.DeserializeAttributeInfoRaw(_buf); Attributes.Add(_e0);}}
        PostInit();
    }

    public static Common DeserializeCommon(ByteBuf _buf)
    {
        return new BuffVoidCaster.Common(_buf);
    }

    public System.Collections.Generic.List<AttributeInfoRaw> Attributes { get; private set; }

    public const int __ID__ = 54582438;
    public override int GetTypeId() => __ID__;

    public override void Resolve(Dictionary<string, object> _tables)
    {
        base.Resolve(_tables);
        foreach(var _e in Attributes) { _e?.Resolve(_tables); }
        PostResolve();
    }

    public override void TranslateText(System.Func<string, string, string> translator)
    {
        base.TranslateText(translator);
        foreach(var _e in Attributes) { _e?.TranslateText(translator); }
    }

    public override string ToString()
    {
        return "{ "
        + "Attributes:" + Bright.Common.StringUtil.CollectionToString(Attributes) + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}
