FIND_PATH(GFLAGS_INCLUDE_DIR gflags/gflags.h)

if(WIN32)
    set(CMAKE_FIND_LIBRARY_PREFIXES "lib" "")
endif()

FIND_LIBRARY(GFLAGS_LIBRARY NAMES gflags
			DOC "The Google Gflags Library"
			)

MARK_AS_ADVANCED(GFLAGS_INCLUDE_DIR GFLAGS_LIBRARY)

include(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(GFLAGS DEFAULT_MSG GFLAGS_LIBRARY GFLAGS_INCLUDE_DIR)

IF(GFLAGS_FOUND)
	SET(GFLAGS_INCLUDE_DIRS ${GFLAGS_INCLUDE_DIR})
	SET(GFLAGS_LIBRARIES    ${GFLAGS_LIBRARY})
ENDIF()