FIND_PATH(GTEST_INCLUDE_DIR gtest/gtest.h)

IF(WIN32)
    SET(CMAKE_FIND_LIBRARY_PREFIXES "lib" "")
ENDIF()

FIND_LIBRARY(GTEST_LIBRARY NAMES gtest
			DOC "The Google Gtest Library"
			)


IF(GTEST_FOUND)
	SET(GTEST_INCLUDE_DIRS ${GTEST_INCLUDE_DIR})
	SET(GTEST_LIBRARIES    ${GTEST_LIBRARY})
ENDIF()

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(GTEST DEFAULT_MSG GTEST_INCLUDE_DIR GTEST_LIBRARY)

MARK_AS_ADVANCED(GTEST_INCLUDE_DIR GTEST_LIBRARY)