FIND_PROGRAM(MONO_EXECUTABLE mono)
FIND_PROGRAM(GMCS_EXECUTABLE gmcs)
FIND_PROGRAM(GACUTIL_EXECUTABLE gacutil)

SET(MONO_FOUND FALSE CACHE INTERNAL "")

FIND_PACKAGE(PkgConfig)

IF(PKG_CONFIG_FOUND)
	EXECUTE_PROCESS(COMMAND ${PKG_CONFIG_EXECUTABLE} --cflags mono-2 --variable=assemblies_dir OUTPUT_VARIABLE MONO_CXX_FLAGS OUTPUT_STRIP_TRAILING_WHITESPACE)
	EXECUTE_PROCESS(COMMAND ${PKG_CONFIG_EXECUTABLE} --libs mono-2 --variable=assemblies_dir OUTPUT_VARIABLE MONO_LINK_FLAGS OUTPUT_STRIP_TRAILING_WHITESPACE)
ENDIF()

MARK_AS_ADVANCED(MONO_EXECUTABLE GMCS_EXECUTABLE GACUTIL_EXECUTABLE MONO_CXX_FLAGS MONO_LINK_FLAGS)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(MONO DEFAULT_MSG MONO_EXECUTABLE GMCS_EXECUTABLE GACUTIL_EXECUTABLE MONO_CXX_FLAGS MONO_LINK_FLAGS)