//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;



namespace ET.Worker
{

public abstract partial class Base :  Bright.Config.BeanBase 
{
    public Base(ByteBuf _buf) 
    {
        PostInit();
    }

    public static Base DeserializeBase(ByteBuf _buf)
    {
        switch (_buf.ReadInt())
        {
            case Worker.OpenUI.__ID__: return new Worker.OpenUI(_buf);
            case Worker.ShowTips.__ID__: return new Worker.ShowTips(_buf);
            case Worker.ShowMessageBox.__ID__: return new Worker.ShowMessageBox(_buf);
            default: throw new SerializationException();
        }
    }



    public virtual void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public virtual void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}
