//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;



namespace ET.Worker
{

public sealed partial class ShowTips :  Base 
{
    public ShowTips(ByteBuf _buf)  : base(_buf) 
    {
        Msg = _buf.ReadString();
        PostInit();
    }

    public static ShowTips DeserializeShowTips(ByteBuf _buf)
    {
        return new Worker.ShowTips(_buf);
    }

    public string Msg { get; private set; }

    public const int __ID__ = 20423749;
    public override int GetTypeId() => __ID__;

    public override void Resolve(Dictionary<string, object> _tables)
    {
        base.Resolve(_tables);
        PostResolve();
    }

    public override void TranslateText(System.Func<string, string, string> translator)
    {
        base.TranslateText(translator);
    }

    public override string ToString()
    {
        return "{ "
        + "Msg:" + Msg + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}
