//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;



namespace ET.Global
{

public sealed partial class GlobalConfig :  Bright.Config.BeanBase 
{
    public GlobalConfig(ByteBuf _buf) 
    {
        Self = _buf.ReadInt();
        PostInit();
    }

    public static GlobalConfig DeserializeGlobalConfig(ByteBuf _buf)
    {
        return new Global.GlobalConfig(_buf);
    }

    public int Self { get; private set; }

    public const int __ID__ = 1131180336;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Self:" + Self + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}
