Import('env')

experimental_env = env.Clone()

experimental_env.Append(LIBS=[
	'gflags',
	'glog',
	'gtest',
	'boost_system',
	'boost_thread'
])

experimental_env.Program('chat/chat_message.cc')
experimental_env.Program('chat/chat_server.cc')
experimental_env.Program('chat/posix_chat_client.cc')
