//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;



namespace ET.MetaBuffMechanism
{

public sealed partial class AttachBuff :  Base 
{
    public AttachBuff(ByteBuf _buf)  : base(_buf) 
    {
        BuffId = _buf.ReadInt();
        PostInit();
    }

    public static AttachBuff DeserializeAttachBuff(ByteBuf _buf)
    {
        return new MetaBuffMechanism.AttachBuff(_buf);
    }

    /// <summary>
    /// 附加Buff时
    /// </summary>
    public int BuffId { get; private set; }
    public BuffConfig BuffId_Ref { get; private set; }

    public const int __ID__ = -133027259;
    public override int GetTypeId() => __ID__;

    public override void Resolve(Dictionary<string, object> _tables)
    {
        base.Resolve(_tables);
        this.BuffId_Ref = (_tables["TbBuff"] as TbBuff).GetOrDefault(BuffId);
        PostResolve();
    }

    public override void TranslateText(System.Func<string, string, string> translator)
    {
        base.TranslateText(translator);
    }

    public override string ToString()
    {
        return "{ "
        + "BuffId:" + BuffId + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}
