//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;



namespace ET.MetaBuffMechanism
{

/// <summary>
/// 这里随便填的，后续根据实际需求设计结构
/// </summary>
public sealed partial class Stun :  Base 
{
    public Stun(ByteBuf _buf)  : base(_buf) 
    {
        Duration = _buf.ReadInt();
        PostInit();
    }

    public static Stun DeserializeStun(ByteBuf _buf)
    {
        return new MetaBuffMechanism.Stun(_buf);
    }

    /// <summary>
    /// 持续回合数
    /// </summary>
    public int Duration { get; private set; }

    public const int __ID__ = 1794504839;
    public override int GetTypeId() => __ID__;

    public override void Resolve(Dictionary<string, object> _tables)
    {
        base.Resolve(_tables);
        PostResolve();
    }

    public override void TranslateText(System.Func<string, string, string> translator)
    {
        base.TranslateText(translator);
    }

    public override string ToString()
    {
        return "{ "
        + "Duration:" + Duration + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}
