//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;



namespace ET
{

public sealed partial class AIConfig :  Bright.Config.BeanBase 
{
    public AIConfig(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);Metas = new System.Collections.Generic.List<AIMeta>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { AIMeta _e0;  _e0 = AIMeta.DeserializeAIMeta(_buf); Metas.Add(_e0);}}
        PostInit();
    }

    public static AIConfig DeserializeAIConfig(ByteBuf _buf)
    {
        return new AIConfig(_buf);
    }

    /// <summary>
    /// Id
    /// </summary>
    public int Id { get; private set; }
    /// <summary>
    /// AIMeta的数据列表
    /// </summary>
    public System.Collections.Generic.List<AIMeta> Metas { get; private set; }

    public const int __ID__ = -294143606;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var _e in Metas) { _e?.Resolve(_tables); }
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var _e in Metas) { _e?.TranslateText(translator); }
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Metas:" + Bright.Common.StringUtil.CollectionToString(Metas) + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}
