//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ET
{
    /// <summary>
    /// 战斗阵营
    /// </summary>
    [System.Flags]
    public enum BattleTeam
    {
        /// <summary>
        /// 中立
        /// </summary>
        Neutral = 1,
        /// <summary>
        /// INC是innocent的缩写
        /// </summary>
        Neutral_INC = 2,
        A = 4,
        B = 8,
        C = 16,
        D = 32,
    }
}
