//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ET
{
    /// <summary>
    /// 可被驱散类型
    /// </summary>
    [System.Flags]
    public enum BuffDispelType
    {
        /// <summary>
        /// 全部
        /// </summary>
        All = 0,
        /// <summary>
        /// 弱
        /// </summary>
        Weak = 1,
        /// <summary>
        /// 强
        /// </summary>
        Strong = 2,
        /// <summary>
        /// 死亡
        /// </summary>
        Death = 4,
        /// <summary>
        /// 登出
        /// </summary>
        Logout = 5,
    }
}
