//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;



namespace ET
{

public sealed partial class BuffTrigger :  Bright.Config.BeanBase 
{
    public BuffTrigger(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Condition = BuffCondition.Base.DeserializeBase(_buf);
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);MetaBuffs = new System.Collections.Generic.List<MetaBuffCfg>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { MetaBuffCfg _e0;  _e0 = MetaBuffCfg.DeserializeMetaBuffCfg(_buf); MetaBuffs.Add(_e0);}}
        PostInit();
    }

    public static BuffTrigger DeserializeBuffTrigger(ByteBuf _buf)
    {
        return new BuffTrigger(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public int Id { get; private set; }
    /// <summary>
    /// 条件
    /// </summary>
    public BuffCondition.Base Condition { get; private set; }
    /// <summary>
    /// 原子（元）buff集合
    /// </summary>
    public System.Collections.Generic.List<MetaBuffCfg> MetaBuffs { get; private set; }

    public const int __ID__ = -1550921275;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        Condition?.Resolve(_tables);
        foreach(var _e in MetaBuffs) { _e?.Resolve(_tables); }
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
        Condition?.TranslateText(translator);
        foreach(var _e in MetaBuffs) { _e?.TranslateText(translator); }
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Condition:" + Condition + ","
        + "MetaBuffs:" + Bright.Common.StringUtil.CollectionToString(MetaBuffs) + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}
