//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;



namespace ET
{

public sealed partial class MetaBuffCfg :  Bright.Config.BeanBase 
{
    public MetaBuffCfg(ByteBuf _buf) 
    {
        Index = _buf.ReadInt();
        Mechanism = MetaBuffMechanism.Base.DeserializeBase(_buf);
        PostInit();
    }

    public static MetaBuffCfg DeserializeMetaBuffCfg(ByteBuf _buf)
    {
        return new MetaBuffCfg(_buf);
    }

    /// <summary>
    /// 索引/顺序
    /// </summary>
    public int Index { get; private set; }
    /// <summary>
    /// 机制，基础效果。比如伤害/属性变化/状态等
    /// </summary>
    public MetaBuffMechanism.Base Mechanism { get; private set; }

    public const int __ID__ = 635878700;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        Mechanism?.Resolve(_tables);
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
        Mechanism?.TranslateText(translator);
    }

    public override string ToString()
    {
        return "{ "
        + "Index:" + Index + ","
        + "Mechanism:" + Mechanism + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}
