//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ET
{
    /// <summary>
    /// 数值
    /// </summary>
    public enum NumericType
    {
        /// <summary>
        /// 最大值，无意义，别配这个
        /// </summary>
        Max = 10000,
        /// <summary>
        /// 力量
        /// </summary>
        Strength = 1001,

        StrengthBase = 1001 * 10 + 1,
        StrengthAdd = 1001 * 10 + 2,
        StrengthPct = 1001 * 10 + 3,
        StrengthFinalAdd = 1001 * 10 + 4,
        StrengthFinalPct = 1001 * 10 + 5,
        /// <summary>
        /// 敏捷
        /// </summary>
        Dexterity = 1002,

        DexterityBase = 1002 * 10 + 1,
        DexterityAdd = 1002 * 10 + 2,
        DexterityPct = 1002 * 10 + 3,
        DexterityFinalAdd = 1002 * 10 + 4,
        DexterityFinalPct = 1002 * 10 + 5,
        /// <summary>
        /// 体质
        /// </summary>
        Constitution = 1003,

        ConstitutionBase = 1003 * 10 + 1,
        ConstitutionAdd = 1003 * 10 + 2,
        ConstitutionPct = 1003 * 10 + 3,
        ConstitutionFinalAdd = 1003 * 10 + 4,
        ConstitutionFinalPct = 1003 * 10 + 5,
        /// <summary>
        /// 智力
        /// </summary>
        Intelligence = 1004,

        IntelligenceBase = 1004 * 10 + 1,
        IntelligenceAdd = 1004 * 10 + 2,
        IntelligencePct = 1004 * 10 + 3,
        IntelligenceFinalAdd = 1004 * 10 + 4,
        IntelligenceFinalPct = 1004 * 10 + 5,
        /// <summary>
        /// 感知
        /// </summary>
        Wisdom = 1005,

        WisdomBase = 1005 * 10 + 1,
        WisdomAdd = 1005 * 10 + 2,
        WisdomPct = 1005 * 10 + 3,
        WisdomFinalAdd = 1005 * 10 + 4,
        WisdomFinalPct = 1005 * 10 + 5,
        /// <summary>
        /// 魅力
        /// </summary>
        Charisma = 1006,

        CharismaBase = 1006 * 10 + 1,
        CharismaAdd = 1006 * 10 + 2,
        CharismaPct = 1006 * 10 + 3,
        CharismaFinalAdd = 1006 * 10 + 4,
        CharismaFinalPct = 1006 * 10 + 5,
        /// <summary>
        /// 生命
        /// </summary>

        [ET.NumericRange(0L,long.MaxValue)]
        HP = 1101,

        HPBase = 1101 * 10 + 1,
        HPAdd = 1101 * 10 + 2,
        HPPct = 1101 * 10 + 3,
        HPFinalAdd = 1101 * 10 + 4,
        HPFinalPct = 1101 * 10 + 5,
        /// <summary>
        /// 能量100时可以发动战略威能
        /// </summary>

        [ET.NumericRange(0L,long.MaxValue)]
        MP = 1102,

        MPBase = 1102 * 10 + 1,
        MPAdd = 1102 * 10 + 2,
        MPPct = 1102 * 10 + 3,
        MPFinalAdd = 1102 * 10 + 4,
        MPFinalPct = 1102 * 10 + 5,
        /// <summary>
        /// 先攻
        /// </summary>
        Initiative = 1103,

        InitiativeBase = 1103 * 10 + 1,
        InitiativeAdd = 1103 * 10 + 2,
        InitiativePct = 1103 * 10 + 3,
        InitiativeFinalAdd = 1103 * 10 + 4,
        InitiativeFinalPct = 1103 * 10 + 5,
        /// <summary>
        /// 速度
        /// </summary>
        Speed = 1104,

        SpeedBase = 1104 * 10 + 1,
        SpeedAdd = 1104 * 10 + 2,
        SpeedPct = 1104 * 10 + 3,
        SpeedFinalAdd = 1104 * 10 + 4,
        SpeedFinalPct = 1104 * 10 + 5,
        /// <summary>
        /// 基础检定加值，不算额外攻击加值
        /// </summary>
        AttackRoll = 1105,

        AttackRollBase = 1105 * 10 + 1,
        AttackRollAdd = 1105 * 10 + 2,
        AttackRollPct = 1105 * 10 + 3,
        AttackRollFinalAdd = 1105 * 10 + 4,
        AttackRollFinalPct = 1105 * 10 + 5,
        /// <summary>
        /// 攻击伤害
        /// </summary>
        Damage = 1106,

        DamageBase = 1106 * 10 + 1,
        DamageAdd = 1106 * 10 + 2,
        DamagePct = 1106 * 10 + 3,
        DamageFinalAdd = 1106 * 10 + 4,
        DamageFinalPct = 1106 * 10 + 5,
        /// <summary>
        /// 攻击加值
        /// </summary>
        AttackBonus = 1107,

        AttackBonusBase = 1107 * 10 + 1,
        AttackBonusAdd = 1107 * 10 + 2,
        AttackBonusPct = 1107 * 10 + 3,
        AttackBonusFinalAdd = 1107 * 10 + 4,
        AttackBonusFinalPct = 1107 * 10 + 5,
        /// <summary>
        /// 伤害加值
        /// </summary>
        DamageBonus = 1108,

        DamageBonusBase = 1108 * 10 + 1,
        DamageBonusAdd = 1108 * 10 + 2,
        DamageBonusPct = 1108 * 10 + 3,
        DamageBonusFinalAdd = 1108 * 10 + 4,
        DamageBonusFinalPct = 1108 * 10 + 5,
        /// <summary>
        /// 防御等级
        /// </summary>
        ArmorClass = 1109,

        ArmorClassBase = 1109 * 10 + 1,
        ArmorClassAdd = 1109 * 10 + 2,
        ArmorClassPct = 1109 * 10 + 3,
        ArmorClassFinalAdd = 1109 * 10 + 4,
        ArmorClassFinalPct = 1109 * 10 + 5,
        /// <summary>
        /// 强韧豁免
        /// </summary>
        ToughSave = 1110,

        ToughSaveBase = 1110 * 10 + 1,
        ToughSaveAdd = 1110 * 10 + 2,
        ToughSavePct = 1110 * 10 + 3,
        ToughSaveFinalAdd = 1110 * 10 + 4,
        ToughSaveFinalPct = 1110 * 10 + 5,
        /// <summary>
        /// 反射豁免
        /// </summary>
        ReflectionSave = 1111,

        ReflectionSaveBase = 1111 * 10 + 1,
        ReflectionSaveAdd = 1111 * 10 + 2,
        ReflectionSavePct = 1111 * 10 + 3,
        ReflectionSaveFinalAdd = 1111 * 10 + 4,
        ReflectionSaveFinalPct = 1111 * 10 + 5,
        /// <summary>
        /// 意志豁免
        /// </summary>
        WillSave = 1112,

        WillSaveBase = 1112 * 10 + 1,
        WillSaveAdd = 1112 * 10 + 2,
        WillSavePct = 1112 * 10 + 3,
        WillSaveFinalAdd = 1112 * 10 + 4,
        WillSaveFinalPct = 1112 * 10 + 5,
        /// <summary>
        /// 剩余动作数量
        /// </summary>
        StandardAction = 1113,

        StandardActionBase = 1113 * 10 + 1,
        StandardActionAdd = 1113 * 10 + 2,
        StandardActionPct = 1113 * 10 + 3,
        StandardActionFinalAdd = 1113 * 10 + 4,
        StandardActionFinalPct = 1113 * 10 + 5,
        /// <summary>
        /// 剩余动作数量
        /// </summary>
        MoveAction = 1114,

        MoveActionBase = 1114 * 10 + 1,
        MoveActionAdd = 1114 * 10 + 2,
        MoveActionPct = 1114 * 10 + 3,
        MoveActionFinalAdd = 1114 * 10 + 4,
        MoveActionFinalPct = 1114 * 10 + 5,
        /// <summary>
        /// 剩余动作数量
        /// </summary>
        FreeAction = 1115,

        FreeActionBase = 1115 * 10 + 1,
        FreeActionAdd = 1115 * 10 + 2,
        FreeActionPct = 1115 * 10 + 3,
        FreeActionFinalAdd = 1115 * 10 + 4,
        FreeActionFinalPct = 1115 * 10 + 5,
        /// <summary>
        /// 剩余动作数量
        /// </summary>
        ReactionsAction = 1116,

        ReactionsActionBase = 1116 * 10 + 1,
        ReactionsActionAdd = 1116 * 10 + 2,
        ReactionsActionPct = 1116 * 10 + 3,
        ReactionsActionFinalAdd = 1116 * 10 + 4,
        ReactionsActionFinalPct = 1116 * 10 + 5,
        /// <summary>
        /// 始终先消耗临时生命
        /// </summary>
        TempHP = 1117,

        TempHPBase = 1117 * 10 + 1,
        TempHPAdd = 1117 * 10 + 2,
        TempHPPct = 1117 * 10 + 3,
        TempHPFinalAdd = 1117 * 10 + 4,
        TempHPFinalPct = 1117 * 10 + 5,
        /// <summary>
        /// Buff层数
        /// </summary>
        BuffLayer = 1201,

        BuffLayerBase = 1201 * 10 + 1,
        BuffLayerAdd = 1201 * 10 + 2,
        BuffLayerPct = 1201 * 10 + 3,
        BuffLayerFinalAdd = 1201 * 10 + 4,
        BuffLayerFinalPct = 1201 * 10 + 5,
        /// <summary>
        /// 累计登录次数
        /// </summary>
        SumLoginNumber = 5001,

        SumLoginNumberBase = 5001 * 10 + 1,
        SumLoginNumberAdd = 5001 * 10 + 2,
        SumLoginNumberPct = 5001 * 10 + 3,
        SumLoginNumberFinalAdd = 5001 * 10 + 4,
        SumLoginNumberFinalPct = 5001 * 10 + 5,
        /// <summary>
        /// 累计登录天数
        /// </summary>
        SumLoginDays = 5002,

        SumLoginDaysBase = 5002 * 10 + 1,
        SumLoginDaysAdd = 5002 * 10 + 2,
        SumLoginDaysPct = 5002 * 10 + 3,
        SumLoginDaysFinalAdd = 5002 * 10 + 4,
        SumLoginDaysFinalPct = 5002 * 10 + 5,
        /// <summary>
        /// 连续登录天数
        /// </summary>
        ContinuousLoginDays = 5003,

        ContinuousLoginDaysBase = 5003 * 10 + 1,
        ContinuousLoginDaysAdd = 5003 * 10 + 2,
        ContinuousLoginDaysPct = 5003 * 10 + 3,
        ContinuousLoginDaysFinalAdd = 5003 * 10 + 4,
        ContinuousLoginDaysFinalPct = 5003 * 10 + 5,
        /// <summary>
        /// 货币金币
        /// </summary>
        CurrencyGold = 5004,

        CurrencyGoldBase = 5004 * 10 + 1,
        CurrencyGoldAdd = 5004 * 10 + 2,
        CurrencyGoldPct = 5004 * 10 + 3,
        CurrencyGoldFinalAdd = 5004 * 10 + 4,
        CurrencyGoldFinalPct = 5004 * 10 + 5,
        /// <summary>
        /// 货币星钻
        /// </summary>
        CurrencyCash = 5005,

        CurrencyCashBase = 5005 * 10 + 1,
        CurrencyCashAdd = 5005 * 10 + 2,
        CurrencyCashPct = 5005 * 10 + 3,
        CurrencyCashFinalAdd = 5005 * 10 + 4,
        CurrencyCashFinalPct = 5005 * 10 + 5,
        /// <summary>
        /// 团队等级
        /// </summary>
        GroupLevel = 5006,

        GroupLevelBase = 5006 * 10 + 1,
        GroupLevelAdd = 5006 * 10 + 2,
        GroupLevelPct = 5006 * 10 + 3,
        GroupLevelFinalAdd = 5006 * 10 + 4,
        GroupLevelFinalPct = 5006 * 10 + 5,
        /// <summary>
        /// 团队声望
        /// </summary>
        GroupExp = 5007,

        GroupExpBase = 5007 * 10 + 1,
        GroupExpAdd = 5007 * 10 + 2,
        GroupExpPct = 5007 * 10 + 3,
        GroupExpFinalAdd = 5007 * 10 + 4,
        GroupExpFinalPct = 5007 * 10 + 5,
        /// <summary>
        /// 团队人数
        /// </summary>
        GroupSize = 5008,

        GroupSizeBase = 5008 * 10 + 1,
        GroupSizeAdd = 5008 * 10 + 2,
        GroupSizePct = 5008 * 10 + 3,
        GroupSizeFinalAdd = 5008 * 10 + 4,
        GroupSizeFinalPct = 5008 * 10 + 5,
        /// <summary>
        /// 团队人数上限
        /// </summary>
        GroupCapacity = 5009,

        GroupCapacityBase = 5009 * 10 + 1,
        GroupCapacityAdd = 5009 * 10 + 2,
        GroupCapacityPct = 5009 * 10 + 3,
        GroupCapacityFinalAdd = 5009 * 10 + 4,
        GroupCapacityFinalPct = 5009 * 10 + 5,
        /// <summary>
        /// 英雄等级
        /// </summary>
        HeroLevel = 5010,

        HeroLevelBase = 5010 * 10 + 1,
        HeroLevelAdd = 5010 * 10 + 2,
        HeroLevelPct = 5010 * 10 + 3,
        HeroLevelFinalAdd = 5010 * 10 + 4,
        HeroLevelFinalPct = 5010 * 10 + 5,
        /// <summary>
        /// 英雄经验
        /// </summary>
        HeroExp = 5011,

        HeroExpBase = 5011 * 10 + 1,
        HeroExpAdd = 5011 * 10 + 2,
        HeroExpPct = 5011 * 10 + 3,
        HeroExpFinalAdd = 5011 * 10 + 4,
        HeroExpFinalPct = 5011 * 10 + 5,
        /// <summary>
        /// 英雄年龄
        /// </summary>
        HeroAge = 5012,

        HeroAgeBase = 5012 * 10 + 1,
        HeroAgeAdd = 5012 * 10 + 2,
        HeroAgePct = 5012 * 10 + 3,
        HeroAgeFinalAdd = 5012 * 10 + 4,
        HeroAgeFinalPct = 5012 * 10 + 5,
        /// <summary>
        /// 英雄属性点数
        /// </summary>
        HeroAbilityPoint = 5013,

        HeroAbilityPointBase = 5013 * 10 + 1,
        HeroAbilityPointAdd = 5013 * 10 + 2,
        HeroAbilityPointPct = 5013 * 10 + 3,
        HeroAbilityPointFinalAdd = 5013 * 10 + 4,
        HeroAbilityPointFinalPct = 5013 * 10 + 5,
        /// <summary>
        /// 冒险地图等级
        /// </summary>
        AdventureLevel = 5014,

        AdventureLevelBase = 5014 * 10 + 1,
        AdventureLevelAdd = 5014 * 10 + 2,
        AdventureLevelPct = 5014 * 10 + 3,
        AdventureLevelFinalAdd = 5014 * 10 + 4,
        AdventureLevelFinalPct = 5014 * 10 + 5,
        /// <summary>
        /// 冒险历史最高等级
        /// </summary>
        AdventureLevelHighest = 5015,

        AdventureLevelHighestBase = 5015 * 10 + 1,
        AdventureLevelHighestAdd = 5015 * 10 + 2,
        AdventureLevelHighestPct = 5015 * 10 + 3,
        AdventureLevelHighestFinalAdd = 5015 * 10 + 4,
        AdventureLevelHighestFinalPct = 5015 * 10 + 5,
        /// <summary>
        /// 竞技场排名
        /// </summary>
        ArenaRank = 5016,

        ArenaRankBase = 5016 * 10 + 1,
        ArenaRankAdd = 5016 * 10 + 2,
        ArenaRankPct = 5016 * 10 + 3,
        ArenaRankFinalAdd = 5016 * 10 + 4,
        ArenaRankFinalPct = 5016 * 10 + 5,
        /// <summary>
        /// 竞技场历史最高榜单级别
        /// </summary>
        ArenaLevelHighest = 5017,

        ArenaLevelHighestBase = 5017 * 10 + 1,
        ArenaLevelHighestAdd = 5017 * 10 + 2,
        ArenaLevelHighestPct = 5017 * 10 + 3,
        ArenaLevelHighestFinalAdd = 5017 * 10 + 4,
        ArenaLevelHighestFinalPct = 5017 * 10 + 5,
        /// <summary>
        /// 竞技场历史最高榜单排名
        /// </summary>
        ArenaRankHighest = 5018,

        ArenaRankHighestBase = 5018 * 10 + 1,
        ArenaRankHighestAdd = 5018 * 10 + 2,
        ArenaRankHighestPct = 5018 * 10 + 3,
        ArenaRankHighestFinalAdd = 5018 * 10 + 4,
        ArenaRankHighestFinalPct = 5018 * 10 + 5,
    }
}
