//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;



namespace ET
{

public sealed partial class PowerConfig :  Bright.Config.BeanBase 
{
    public PowerConfig(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Name = _buf.ReadString();
        Type = _buf.ReadString();
        Class = _buf.ReadString();
        Level = _buf.ReadInt();
        Hierarchy = _buf.ReadString();
        UseEquip = _buf.ReadString();
        UseWeapon = _buf.ReadString();
        ActionType = _buf.ReadString();
        AttackRoll = _buf.ReadString();
        DefenceRoll = _buf.ReadString();
        PostInit();
    }

    public static PowerConfig DeserializePowerConfig(ByteBuf _buf)
    {
        return new PowerConfig(_buf);
    }

    /// <summary>
    /// Id
    /// </summary>
    public int Id { get; private set; }
    /// <summary>
    /// 名称
    /// </summary>
    public string Name { get; private set; }
    /// <summary>
    /// 类型
    /// </summary>
    public string Type { get; private set; }
    /// <summary>
    /// 职业
    /// </summary>
    public string Class { get; private set; }
    /// <summary>
    /// 等级
    /// </summary>
    public int Level { get; private set; }
    /// <summary>
    /// 层次
    /// </summary>
    public string Hierarchy { get; private set; }
    /// <summary>
    /// 需要装备类型
    /// </summary>
    public string UseEquip { get; private set; }
    /// <summary>
    /// 需要武器类型
    /// </summary>
    public string UseWeapon { get; private set; }
    /// <summary>
    /// 动作类型
    /// </summary>
    public string ActionType { get; private set; }
    /// <summary>
    /// 攻击检定
    /// </summary>
    public string AttackRoll { get; private set; }
    /// <summary>
    /// 防御检定
    /// </summary>
    public string DefenceRoll { get; private set; }

    public const int __ID__ = 1646332039;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Name:" + Name + ","
        + "Type:" + Type + ","
        + "Class:" + Class + ","
        + "Level:" + Level + ","
        + "Hierarchy:" + Hierarchy + ","
        + "UseEquip:" + UseEquip + ","
        + "UseWeapon:" + UseWeapon + ","
        + "ActionType:" + ActionType + ","
        + "AttackRoll:" + AttackRoll + ","
        + "DefenceRoll:" + DefenceRoll + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}
