//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;



namespace ET
{

public sealed partial class ServerInfoConfig :  Bright.Config.BeanBase 
{
    public ServerInfoConfig(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        ServerName = _buf.ReadString();
        PostInit();
    }

    public static ServerInfoConfig DeserializeServerInfoConfig(ByteBuf _buf)
    {
        return new ServerInfoConfig(_buf);
    }

    /// <summary>
    /// Id
    /// </summary>
    public int Id { get; private set; }
    /// <summary>
    /// 区服名称
    /// </summary>
    public string ServerName { get; private set; }

    public const int __ID__ = -1669631661;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "ServerName:" + ServerName + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}
