//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ET
{
    public enum SkillRange
    {
        /// <summary>
        /// 无限制
        /// </summary>
        Unlimited = 0,
        /// <summary>
        /// 近身
        /// </summary>
        Close = 1,
        /// <summary>
        /// 近距
        /// </summary>
        NearDistance = 2,
        /// <summary>
        /// 远距
        /// </summary>
        FarDistance = 3,
        /// <summary>
        /// 范围
        /// </summary>
        Area = 4,
    }
}
