//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;

namespace ET
{
   
public partial class TbServerInfo
{
    private readonly Dictionary<int, ServerInfoConfig> _dataMap;
    private readonly List<ServerInfoConfig> _dataList;
    
    public TbServerInfo(ByteBuf _buf)
    {
        _dataMap = new Dictionary<int, ServerInfoConfig>();
        _dataList = new List<ServerInfoConfig>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            ServerInfoConfig _v;
            _v = ServerInfoConfig.DeserializeServerInfoConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
        PostInit();
    }

    public Dictionary<int, ServerInfoConfig> DataMap => _dataMap;
    public List<ServerInfoConfig> DataList => _dataList;

    public ServerInfoConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public ServerInfoConfig Get(int key) => _dataMap[key];
    public ServerInfoConfig this[int key] => _dataMap[key];

    public void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}