//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ET
{
    public enum UnitType
    {
        /// <summary>
        /// 无
        /// </summary>
        None = 0,
        /// <summary>
        /// 玩家
        /// </summary>
        Player = 1,
        /// <summary>
        /// 战斗
        /// </summary>
        Battle = 2,
        /// <summary>
        /// 物品
        /// </summary>
        Item = 3,
        Npc = 4,
        /// <summary>
        /// 冒险
        /// </summary>
        Adventure = 5,
        /// <summary>
        /// 障碍物
        /// </summary>
        Obstacle = 6,
        /// <summary>
        /// 虚空施放者
        /// </summary>
        VoidCaster = 7,
    }
}
