
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ET
{ 
    public enum ENumericValueType
    {
        /// <summary>
        /// EV_None
        /// </summary>
        None = 0,
        /// <summary>
        /// EV_Init
        /// </summary>
        Int = 1,
        /// <summary>
        /// EV_Long
        /// </summary>
        Long = 2,
        /// <summary>
        /// EV_Bool
        /// </summary>
        Bool = 3,
        /// <summary>
        /// EV_Float
        /// </summary>
        Float = 4,
    }

} 

