
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{

    [Config]
    public partial class NumericLocalizationConfigCategory : Singleton<NumericLocalizationConfigCategory>, ILubanConfig
    {
        private readonly Dictionary<ENumericType, NumericLocalizationConfig> _dataMap;
        private readonly List<NumericLocalizationConfig> _dataList;
        
        public NumericLocalizationConfigCategory(ByteBuf _buf)
        {
            _dataMap = new Dictionary<ENumericType, NumericLocalizationConfig>();
            _dataList = new List<NumericLocalizationConfig>();
            
            for(int n = _buf.ReadSize() ; n > 0 ; --n)
            {
                NumericLocalizationConfig _v;
                _v = NumericLocalizationConfig.DeserializeNumericLocalizationConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }
            EndInit();
        }

        public Dictionary<ENumericType, NumericLocalizationConfig> GetAll() => _dataMap;
        public Dictionary<ENumericType, NumericLocalizationConfig> DataMap => _dataMap;
        public List<NumericLocalizationConfig> DataList => _dataList;

        public NumericLocalizationConfig GetOrDefault(ENumericType key) => _dataMap.GetValueOrDefault(key);

        public NumericLocalizationConfig Get(ENumericType key)
        {
            if (_dataMap.TryGetValue(key,out var v))
            {
                return v;
            }
            LubanLog.Error(this,key);
            return default;
        }

        public void ResolveRef()
        {
            foreach(var _v in _dataList)
            {
                _v.ResolveRef();
            }
            EndRef();
        }


        partial void EndRef();
    }

}

